export const blogList = [
    {
        id: 1,
        title: '7 CSS tools you should be using ',
        category: 'development',
        subCategory: ['frontend', 'ui/ux', 'design'],
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/designer-1.jpg',
    },
    {
        id: 2,
        title: 'Thành phố Huế',
        category: 'travel',
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description:
            "Huế – mảnh đất lãng mạn, mộng mơ, đậm chất thơ, một miền di sản có một không hai về vẻ đẹp rất riêng, rất ngọt ngào. Khi chưa đặt chân đến Huế, tôi không mường tượng được một cố đô đầy chất thơ sẽ ra sao giữa thời hiện đại. Nhìn cuộc sống sôi động, ồn ào, náo nhiệt không ngừng ở Thủ đô Hà Nội và tp Hồ Chí Minh, tôi bất chợt lo lắng cho thành phố nhỏ, thơ mộng ấy dường như chỉ xuất hiện trong thơ ca, nhạc họa và nhiếp ảnh… Thế rồi, tôi cũng đến Huế. Huế đón chào tôi giống như khi tôi ngắm Huế qua những bức ảnh, thơ ca… Thật bình yên, thơ mộng đến lạ kỳ, Huế bình lặng từ cảnh vật đến con người. Từ nụ cười dịu dàng, kín đáo sau vành nón lá của các cô gái Huế đạp xe trên phố cho đến nét đôn hậu vô tư của bà chủ quán hàng ăn, tay thoăn thoắt xếp bánh bèo cho khách đang nôn nóng chờ đợi… Huế có sông Hương hiền hòa thơ mộng, có núi Ngự thông reo vi vu giữa trời xanh. Huế có Kinh thành, nơi chứng kiến biết bao sự đổi thay quyền cai trị đất nước, lúc thịnh lúc suy. Huế có lăng tẩm đền đài lưu dấu ngàn thu của các bậc Vua chúa. Huế có Từ Đàm, ngôi Phạm Vũ đã chứng tri biết bao biến động thăng trầm hào hùng của lịch sử nước nhà. Huế có Thiên Mụ, ngôi cổ tự hùng thiêng trải qua bao thế hệ. Những hồi chuông Thiên Mụ còn mãi ngân vang từ ngàn xưa cho tới tận ngàn đời sau. Tháp Phước Duyên vời vợi giữa chốn Kinh kỳ, như thâu gọn hồn thiêng của Tổ quốc.",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/hue.jpg',
    },
    {
        id: 3,
        title: 'Aeon Mall Tân Phú',
        category: 'shopping',
        subCategory: ['e-commerce store', 'clothing', 'shopping store'],
        description:
            "Khai trương từ tháng 6, đến nay, Aeon Mall Bình Tân đã đổi mới về cửa hàng mua sắm và chú trọng nâng cấp không gian cùng cơ sở vật chất, đem đến nhiều bất ngờ cho khách hàng. Với tổng số 47 cửa hàng mới được khai trương, mở rộng quy mô hoạt động lên đến gần 150 cửa hàng, Aeon Mall Bình Tân ngày càng đa dạng sự lựa chọn cho khách hàng đến tham quan và mua sắm từ ngành hàng thời trang, mỹ phẩm, nội thất, làm đẹp đến ăn uống... Nhiều cửa hàng mỹ phẩm, phụ kiện khai trương mới, giúp khách hàng có cơ hội mua sắm nhiều sản phẩm đến từ các thương hiệu nổi tiếng trong và ngoài nước. Những gian hàng ẩm thực đa dạng mang đến nhiều món ngon từ khắp các vùng miền của Việt Nam và nhiều nước trên thế giới.            Bên cạnh đổi mới về cửa hàng mua sắm, Aeon Mall Bình Tân còn cải tạo nhiều bàn ghế, khu vực nghỉ chân cho khách hàng, đặc biệt là không gian vui chơi và phòng nghỉ cho trẻ.",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/aeon.jpg',
    },
    {
        id: 4,
        title: 'ADVENTURE IN YOU',
        category: 'adventure',
        subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
        description:
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/graphic-design-trends.png',
    },
    {
        id: 5,
        title: 'Bánh mì Việt Nam',
        category: 'cooking',
        subCategory: ['mobilefood', 'food', 'lifestyle'],
        description:
            "Bánh mì Việt Nam (gọi tắt: bánh mì) là một món ăn Việt Nam, với lớp vỏ ngoài là một ổ bánh mì nướng có da giòn, ruột mềm, còn bên trong là phần nhân. Tùy theo văn hóa vùng miền hoặc sở thích cá nhân, người ta có thể chọn nhiều nhân bánh mì khác nhau. Tuy nhiên, loại nhân bánh truyền thống thường chứa chả lụa, thịt, cá, thực phẩm chay hoặc mứt trái cây, kèm theo một số nguyên liệu phụ khác như patê, bơ, rau, ớt và đồ chua. Bánh mì được xem như một loại thức ăn nhanh bình dân và thường được tiêu thụ trong bữa sáng hoặc bất kỳ bữa phụ nào trong ngày. Do có giá thành phù hợp nên bánh mì trở thành món ăn được rất nhiều người ưa chuộng. Bánh mì Việt Nam có gốc từ bánh baguette, do người Pháp đưa vào miền Nam Việt Nam trong thế kỷ 20. Một số nhà nghiên cứu cho rằng món bánh mì đã có mặt tại Việt Nam từ 150 năm trước.[2] Những thập kỉ sau, bánh mì Việt Nam lan ra khắp miền Trung và miền Nam, đặc biệt là ở Sài Gòn. Người Sài Gòn sau đó cải biên chiếc bánh baguette thành ổ bánh mì nhỏ và ngắn hơn, chỉ còn khoảng 30–40 cm, còn ruột bánh thì rỗng hơn để đưa được nhiều nhân, tương tự như món sandwich. Tùy thuộc vào thành phần nhân, bánh mì có những tên gọi khác nhau. Ngoài ra, bánh mì còn ăn kèm với nhiều món ăn đa dạng, chẳng hạn như thịt bò kho, cá mòi hay xíu mại.",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/banhmi.jpg',
    },
    {
        id: 6,
        title: 'Đà Lạt quê tôi',
        category: 'travel',
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description:
            " Giữa hạ, tôi có dịp trở lại Đà Lạt. Đà Lạt bây giờ thay đổi nhiều. Trung tâm phố thị dường như chật chội hơn. Nhiều nhà hộp, nhà vuông bên cạnh những đường ngõ bê tông ám mùi khói nhạt của xe cộ nườm nượp mùa cao điểm du lịch, hàng quán, buôn bán ồn ào bủa vây. Đà Lạt giờ có nhiều những khu vườn kính phủ trắng đầy đồi trọc, chỉ còn những hàng thông lác đác mãi vùng ngoại ô; những hàng quán màu mè, cố giả nét xưa cho bọn trẻ thời thượng chen nhau check-in… May sao, Đà Lạt vẫn còn vùng ngoại ô Cầu Đất nằm thoải, yên ắng thở nhịp thở an bình, mướt mát, xanh trong. Nơi đây vẫn còn đám thông già, vẫn còn những vạt chè non, còn vườn hồng đương chờ thu lá xanh mướt chen chúc cùng quả. Vẫn còn những lối nhỏ về thưa vắng, khi chiều, ướt mi mắt trong sương....",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/dalat.gif',
    },
    {
        id: 7,
        title: 'Art & Perception',
        category: 'art',
        subCategory: ['skill', 'design', 'passion'],
        description:
            "The main objective of Art & Perception is to provide a high-quality platform to publish new artwork and research in the multi-disciplinary emerging bridge between art and perception. As such it aims to become the top venue to explore the links between the science of perception and the arts, and to bring together artists, researchers, scholars and students in a unified community that can cooperate, discuss and develop new scientific perspectives in this complex and intriguing new field. The purpose is not to minimize or erase the differences between the arts and sciences, which are grounded in venerable histories that are in many ways necessarily distinct. Rather, the ambition of the journal is to combine the differing methods and insights of artists and scientists in order to expand our knowledge of art and perceptual experience in a way that neither could do alone.",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/Synthwave-Postmodern.jpg',
    },
    {
        id: 8,
        title: 'Thủ Đô Hà Nội',
        category: 'travel',
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description:
            "Hà Nội của tôi có gì đẹp? Câu hỏi này thật khó trả lời. Vì lẽ, đối với tôi những gì thân quen luôn đẹp, luôn bình yên. Hà Nội “bình minh” sớm hơn Sài Gòn một nhịp. Chỉ 4, 5h sáng đã thấy nhộn nhịp những người rủ nhau tập thể dục dưỡng sinh, chạy bộ. Sau bước khởi động cho ngày mới là một ly cà phê đậm đà trước bữa sáng, rồi mọi người tất bật đi làm. Khoảng thời gian này và giờ tan tầm luôn là ác mộng với tôi. Từ nhà tôi tới trường xe cộ đi lại nườm nượp. Mất cả giờ đồng hồ để thoát khỏi vòng vây của những chiếc xe. Dù mà Đông hay mùa Hè thì tắc đường cũng là nỗi kinh hoàng. Đó là mặt trái của thành phố đang phát triển này. Một bào thai đang chờ sinh luôn làm bà mẹ đau đớn. Nhưng cũng như sự chào đời của đứa trẻ là niềm hạnh phúc của gia đình. Hà Nội tắc đường lại tạo nên nét riêng của thành phố này.",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/hanoi.jpg',
    },
    {
        id: 9,
        title: 'Cơm chiên',
        category: 'cooking',
        subCategory: ['family', 'food', 'lifestyle'],
        description:
            "Với cách làm cơm chiên lạp xưởng từ một chút cơm nguội, lạp xưởng, dưa chuột, hành lá,…từ cá khô một nắng. Tôi chắc chắn bạn sẽ chuẩn bị cho gia đình bữa sáng vừa ngon, tiết kiệm thời gian lại vô cùng chắc bụng. Chúc bạn và gia đình có bữa sáng tuyệt vời tiết kiệm thời gian với món cơm chiên lạp xưởng!",
        authorName: 'Minh Tri',
        authorAvatar: '/assets/images/author.jpg',
        createdAt: 'June 03, 2021',
        cover: '/assets/images/comchien.jpeg',
    },

];